修改缩进，继续前进

diff --git a/.github/workflows/release-package.yml b/.github/workflows/release-package.yml
--- a/.github/workflows/release-package.yml
+++ b/.github/workflows/release-package.yml
@@ -23,17 +23,17 @@ jobs:
         echo "::set-output name=commit_message::$(git log --format=%B -n 1 $GITHUB_SHA)"
 
     - name: Check if version changed
-        id: versionchanged
-        run: |
-          PREVIOUS_VERSION=$(cat previous_version.txt)
-          CURRENT_VERSION=${{ steps.package.outputs.version }}
-          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
-            echo "Version has changed. Proceeding with release..."
-            echo "$CURRENT_VERSION" > previous_version.txt
-          else
-            echo "Version has not changed. Skipping release..."
-            exit 78  # This exits the workflow without failing it
-          fi
+      id: versionchanged
+      run: |
+        PREVIOUS_VERSION=$(cat previous_version.txt)
+        CURRENT_VERSION=${{ steps.package.outputs.version }}
+        if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
+          echo "Version has changed. Proceeding with release..."
+          echo "$CURRENT_VERSION" > previous_version.txt
+        else
+          echo "Version has not changed. Skipping release..."
+          exit 78  # This exits the workflow without failing it
+        fi
           
     - name: Create Release
       id: create_release
