提交不变版本号

diff --git a/.github/workflows/release-package.yml b/.github/workflows/release-package.yml
--- a/.github/workflows/release-package.yml
+++ b/.github/workflows/release-package.yml
@@ -30,10 +30,9 @@ jobs:
           if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
             echo "Version has changed. Proceeding with release..."
             echo "$CURRENT_VERSION" > previous_version.txt
-            echo "::set-output name=version_changed::true"
           else
             echo "Version has not changed. Skipping release..."
-            echo "::set-output name=version_changed::false"
+            exit 78  # This exits the workflow without failing it
           fi
           
     - name: Create Release
